include:
  - file: "/build/node/template-react-yarn.yml"
    project: "platform/pipelines-templates"
    ref: "master"
  - file: "/build/node/template-react-yarn-test-latest.yml"
    project: "platform/pipelines-templates"
    ref: "master"

test:
  script:
    - yarn lint
    - yarn coverage

.docker-job:
  variables:
    COMMIT_SHA_FILEPATH: /etc/nginx/commit.sha

default:
  image: node:20-alpine

variables:
  IMAGE_NAME: vuhl-api-portal/demo-webcomponents-library-template

cdn-release:
  stage: deploy
  image: miaplatform/cdn-publish:0.6.0
  needs:
    - install-dependencies
    - build-site
    - test
    - test-latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - yarn install --frozen-lockfile
    - yarn build
  script:
    - cdn publish -k "$CDN_STORAGE_ACCESS_KEY" -s mia-platform-test -b 20
